import type { LessonDef } from '../../types';

export const rotationsAxes: LessonDef = {
  id: 'rotations-axes',
  moduleId: 'm03-quantum-gates',
  contentVersion: '1.0.0',
  title: 'Rotations & Phase Gates (S, T, Rθ)',
  type: 'learn',
  typeLabel: 'Concept',
  duration: '15 min',
  summary: 'Arbitrary angle rotations on the Bloch sphere, the Clifford group, and T-gate universality.',
  status: 'available',

  completionRequirements: [
    { type: 'checkpoint', id: 'cp-rotations-01' },
    { type: 'visual_interaction', id: 'vis-rotations-bloch' },
  ],

  blocks: [
    {
      type: 'text',
      content: 'While Pauli gates flip states by 180° (π radians), quantum control pulses generated by microwave synthesizers can rotate the statevector by **any arbitrary continuous angle θ**. Understanding these continuous rotations is crucial for variational quantum algorithms (VQE, QAOA) and quantum pulse synthesis.',
    },
    { type: 'divider' },

    { type: 'heading', level: 2, content: 'Rotation Operators Rx, Ry, Rz' },
    {
      type: 'text',
      content: 'For any axis along unit vector n̂ and angle θ, the rotation operator is given by the matrix exponential of the Pauli operators:',
    },
    {
      type: 'math',
      expression: 'R_n(\\theta) = \\exp\\left(-i \\frac{\\theta}{2} \\hat{n} \\cdot \\vec{\\sigma}\\right) = \\cos\\left(\\frac{\\theta}{2}\\right) I - i \\sin\\left(\\frac{\\theta}{2}\\right) (\\hat{n} \\cdot \\vec{\\sigma})',
      display: true,
      label: 'General Bloch rotation',
    },
    {
      type: 'text',
      content: 'For rotations around the three cardinal axes X, Y, and Z:',
    },
    {
      type: 'math',
      expression: 'R_x(\\theta) = \\begin{pmatrix} \\cos\\frac{\\theta}{2} & -i\\sin\\frac{\\theta}{2} \\\\ -i\\sin\\frac{\\theta}{2} & \\cos\\frac{\\theta}{2} \\end{pmatrix}, \\quad R_z(\\theta) = \\begin{pmatrix} e^{-i\\theta/2} & 0 \\\\ 0 & e^{i\\theta/2} \\end{pmatrix}',
      display: true,
      label: 'Rx and Rz matrices',
    },

    { type: 'divider' },

    { type: 'heading', level: 2, content: 'Discrete Phase Gates: S and T' },
    {
      type: 'text',
      content: 'Two discrete rotations around the Z-axis appear in standard quantum fault-tolerant architectures:',
    },
    {
      type: 'math',
      expression: 'S = \\begin{pmatrix} 1 & 0 \\\\ 0 & i \\end{pmatrix} = R_z(\\pi/2), \\qquad T = \\begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\\pi/4} \\end{pmatrix} = R_z(\\pi/4)',
      display: true,
      label: 'Phase (S) and T gates',
    },
    {
      type: 'callout',
      variant: 'insight',
      title: 'T-Gate Universality & Fault Tolerance',
      content: 'The set {H, S, CNOT} forms the Clifford group. By the Gottesman-Knill theorem, any quantum circuit containing only Clifford gates can be efficiently simulated on a classical computer in polynomial time. Adding the non-Clifford **T gate** makes the gate set **universal**, enabling full quantum advantage.',
    },

    { type: 'divider' },

    { type: 'heading', level: 2, content: 'Interactive Bloch Vector Rotations' },
    {
      type: 'interactive_visual',
      id: 'vis-rotations-bloch',
      visualKey: 'blochSphere',
      caption: 'The Bloch sphere representing rotations in state space.',
      interactionPrompt: 'Rotate the state vector to observe how polar angle θ and azimuthal phase angle φ correspond to continuous gate parameters.',
    },

    { type: 'divider' },

    {
      type: 'checkpoint',
      id: 'cp-rotations-01',
      question: 'Applying the phase gate S to the state |+⟩ = (|0⟩ + |1⟩)/√2 produces which quantum state?',
      options: [
        { key: 'a', text: '(|0⟩ + i|1⟩)/√2' },
        { key: 'b', text: '(|0⟩ - |1⟩)/√2' },
        { key: 'c', text: 'i(|0⟩ + |1⟩)/√2' },
        { key: 'd', text: '|1⟩' },
      ],
      correctKey: 'a',
      incorrectExplanations: {
        b: 'This is |−⟩, which is obtained by applying Z, not S. S applies a 90° (π/2) phase, not 180° (π).',
        c: 'S acts selectively on |1⟩: S|0⟩ = |0⟩ and S|1⟩ = i|1⟩. It does not multiply the global state by i.',
        d: 'S is a phase rotation; it does not change the probability distribution between |0⟩ and |1⟩.',
      },
      correctExplanation: 'Correct! S|0⟩ = |0⟩ and S|1⟩ = i|1⟩. Therefore, S|+⟩ = (|0⟩ + i|1⟩)/√2, which lies along the positive Y-axis on the equator of the Bloch sphere (|y+⟩).',
    },
  ],
};
