import type { ModuleDef } from '../../types';
import { coreLesson } from '../coreLessonFactory';
const moduleId = 'm04-superposition-interference';
const lessons = [
  coreLesson({ id:'global-vs-relative-phase', moduleId, title:'Global vs Relative Phase', summary:'Learn which phase changes are observable and how interference reveals relative phase.', concept:'Multiplying an entire state by one phase does not change physical predictions. A phase difference between basis amplitudes becomes observable after a basis change.', equation:'e^{iγ}|ψ⟩ ~ |ψ⟩,    |+⟩ = (|0⟩+|1⟩)/√2,    |−⟩ = (|0⟩−|1⟩)/√2', equationLabel:'Global-phase equivalence and relative phase', misconception:'Equal Z-basis probabilities do not imply equal states. |+⟩ and |−⟩ both produce 50/50 Z counts.', prediction:'Predict H-Z-H acting on |0⟩.', question:'Which experiment distinguishes |+⟩ from |−⟩?', options:[{key:'a',text:'Measure both directly in Z'},{key:'b',text:'Apply H, then measure Z'},{key:'c',text:'Count the qubits'},{key:'d',text:'Multiply both by −1'}], correctKey:'b', correctExplanation:'H converts the relative phase into a measurable population difference.', labLink:'/labs/guided/phase', labLabel:'Relative phase guided lab', reflection:'Why can phase matter while remaining invisible in the current basis?' }),
  coreLesson({ id:'mach-zehnder', moduleId, title:'Interference as Path Recombination', summary:'Connect Hadamard interference to a two-path interferometer.', concept:'The first Hadamard creates two coherent paths; phase accumulates; the second recombines their amplitudes.', equation:'P(0)=cos²(φ/2),    P(1)=sin²(φ/2)', equationLabel:'Interferometer output probabilities', misconception:'The second Hadamard recombines amplitudes; it does not add randomness.', prediction:'At φ=π, which state is detected?', question:'What happens for H-H on |0⟩?', options:[{key:'a',text:'Always |0⟩'},{key:'b',text:'Always |1⟩'},{key:'c',text:'50/50 mixture'},{key:'d',text:'Invalid state'}], correctKey:'a', correctExplanation:'The paths interfere constructively for |0⟩ and destructively for |1⟩.', labLink:'/labs/guided/superposition', labLabel:'Superposition and interference lab', reflection:'How is adding amplitudes different from adding probabilities?' }),
  coreLesson({ id:'interference-experiment', moduleId, title:'Build an Interference Experiment', summary:'Use recombination as an operational test of coherence.', type:'experiment', concept:'A coherent superposition retains relative phase and can be reversed. An incoherent 50/50 mixture cannot reconstruct a deterministic output.', equation:'ρ+ = |+⟩⟨+|  ≠  ½|0⟩⟨0| + ½|1⟩⟨1|', equationLabel:'Coherent state versus mixture', misconception:'A 50/50 histogram alone cannot certify superposition.', prediction:'Compare H-H with H-measure-reset-H.', question:'What best demonstrates coherence?', options:[{key:'a',text:'A single 0'},{key:'b',text:'A 50/50 histogram'},{key:'c',text:'Deterministic reconstruction'},{key:'d',text:'More shots'}], correctKey:'c', correctExplanation:'Reconstruction requires relative phase preserved by coherence.', labLink:'/labs/guided/measurement', labLabel:'Measurement and reset lab', reflection:'Which operation destroys phase information?' }),
  coreLesson({ id:'phase-challenge', moduleId, title:'Phase-Sensitive Assessment', summary:'Debug circuits whose counts look right but phase is wrong.', type:'challenge', concept:'Rigorous grading compares complex states or phase-sensitive observables. One histogram can accept an orthogonal state.', equation:'Fψ = |⟨ψtarget|ψ⟩|²', equationLabel:'Pure-state fidelity', misconception:'Matching one histogram is not preparing the target state.', prediction:'Would |Φ−⟩ pass a count-only |Φ+⟩ test?', question:'What is their fidelity?', options:[{key:'a',text:'1'},{key:'b',text:'0.5'},{key:'c',text:'0'},{key:'d',text:'Shot-dependent'}], correctKey:'c', correctExplanation:'The Bell states are orthogonal, so fidelity is zero.', labLink:'/challenges/bell-phase-verification', labLabel:'Bell hidden-phase challenge', reflection:'Why combine fidelity, constraints and test cases?' }),
];
export const m04SuperpositionInterference: ModuleDef = { id:moduleId, number:'04', title:'Superposition, Phase & Interference', subtitle:'Constructive and destructive amplitude interference', description:'Turn complex amplitudes and relative phase into observable evidence.', status:'available', lessons };
