import type { ModuleDef } from '../../types';
import { coreLesson } from '../coreLessonFactory';
const moduleId = 'm05-entanglement-correlation';
const lessons = [
  coreLesson({ id:'cnot-entangler', moduleId, title:'When CNOT Creates Entanglement', summary:'Identify when a controlled gate entangles two qubits.', concept:'CNOT entangles only when a coherent control alternative becomes correlated with the target. Basis inputs remain product states.', equation:'CNOT(|+⟩|0⟩) = (|00⟩+|11⟩)/√2', equationLabel:'CNOT entanglement condition', misconception:'CNOT does not entangle every input.', prediction:'Compare CNOT on |00⟩ and |+0⟩.', question:'Which input produces a Bell pair?', options:[{key:'a',text:'|00⟩'},{key:'b',text:'|10⟩'},{key:'c',text:'|+0⟩'},{key:'d',text:'|01⟩'}], correctKey:'c', correctExplanation:'The superposed control creates a non-separable correlation.', labLink:'/labs/guided/bell-state', labLabel:'Bell-state guided lab', reflection:'How would you prove the output is not a product state?' }),
  coreLesson({ id:'bell-states', moduleId, title:'The Four Bell States', summary:'Construct and distinguish the entangled two-qubit basis.', concept:'Local X and Z operations transform Bell states without changing maximal entanglement.', equation:'|Φ±⟩=(|00⟩±|11⟩)/√2,    |Ψ±⟩=(|01⟩±|10⟩)/√2', equationLabel:'Bell basis', misconception:'Correlation alone does not identify a Bell state; phase matters.', prediction:'Apply Z to |Φ+⟩.', question:'Which operation maps |Φ+⟩ to |Ψ+⟩?', options:[{key:'a',text:'X on either qubit'},{key:'b',text:'Z on either qubit'},{key:'c',text:'H on both'},{key:'d',text:'Measurement'}], correctKey:'a', correctExplanation:'A bit flip changes equal pairs into opposite pairs.', labLink:'/explore/algorithms/bell-state', labLabel:'Four Bell states laboratory', reflection:'Why are Z counts insufficient to determine ±?' }),
  coreLesson({ id:'correlation-inspector', moduleId, title:'Correlation Is Not Signalling', summary:'Separate entanglement from communication using marginals.', concept:'Entangled outcomes can be correlated while each local marginal stays random. No controllable message travels faster than light.', equation:'PB(0)=Σa P(a,0)=½,    PB(1)=½', equationLabel:'No-signalling marginal', misconception:'Instant correlation is not instant communication.', prediction:'Can Bob detect whether Alice measured from his outcomes?', question:'What does Bob observe locally?', options:[{key:'a',text:'Alice’s bit'},{key:'b',text:'A deterministic sequence'},{key:'c',text:'A 50/50 marginal'},{key:'d',text:'No outcomes'}], correctKey:'c', correctExplanation:'Correlation appears only after classical comparison.', labLink:'/labs/conflict?lab=lab-m02-no-signaling', labLabel:'No-signalling conflict lab', reflection:'What classical information must be exchanged?' }),
  coreLesson({ id:'teleportation-challenge', moduleId, title:'Teleportation and Classical Feed-Forward', summary:'Trace entanglement, Bell measurement and corrections.', type:'challenge', concept:'Teleportation transfers an unknown state using entanglement and two classical bits. It consumes the original and does not transmit matter.', equation:'|ψ⟩⊗|Φ+⟩ → BSM(m1,m2),    |ψ⟩B = Z^m1 X^m2 |φ⟩B', equationLabel:'Teleportation correction rule', misconception:'Teleportation neither clones nor avoids classical communication.', prediction:'What can Bob recover before Alice’s bits arrive?', question:'Why is no-cloning respected?', options:[{key:'a',text:'Bob gets a copy'},{key:'b',text:'Alice’s measurement destroys the original'},{key:'c',text:'It was classical'},{key:'d',text:'No entanglement'}], correctKey:'b', correctExplanation:'The Bell measurement consumes the original state.', labLink:'/explore/teleportation', labLabel:'Teleportation protocol lab', reflection:'Where do quantum resources end and classical communication begin?' }),
];
export const m05EntanglementCorrelation: ModuleDef = { id:moduleId, number:'05', title:'Entanglement & Correlation', subtitle:'Bell states, no-signalling and teleportation', description:'Build Bell states, test no-signalling and follow state transfer.', status:'available', lessons };
