"""Authoritative Quantum Framework Code Generators.

Translates canonical CircuitIR into verified target code for:
- OpenQASM 3 (deterministic canonical serialization)
- Qiskit (Python)
- Google Cirq (Python)
- Xanadu PennyLane (Python)
"""

from typing import Literal
from .ir import CircuitIR
from .qasm_serializer import serialize_ir_to_openqasm3, _format_param
from .gate_registry import get_gate_definition


ExportFormat = Literal["openqasm3", "qiskit", "cirq", "pennylane"]


def to_openqasm3(circuit: CircuitIR) -> str:
    """Produces canonical OpenQASM 3 code."""
    return serialize_ir_to_openqasm3(circuit)


def to_qiskit(circuit: CircuitIR) -> str:
    """Produces executable Python Qiskit code."""
    lines = [
        "# Generated by Quantum Lens AI Compiler",
        "from qiskit import QuantumCircuit",
        "from math import pi",
        "",
        f"qc = QuantumCircuit({circuit.qubits}, {circuit.classicalBits})",
        "",
    ]

    for op in circuit.operations:
        op_type = op.type.upper()

        if op_type == "GATE":
            gate_name = op.gate.lower() if op.gate else "unknown"
            # Format params if any
            params_str = ", ".join(_format_param(p) for p in op.params)

            # Ordered operands: controls first, then targets
            operands = [str(c) for c in op.controls] + [str(t) for t in op.targets]
            operands_str = ", ".join(operands)

            if op.params:
                lines.append(f"qc.{gate_name}({params_str}, {operands_str})")
            else:
                lines.append(f"qc.{gate_name}({operands_str})")

        elif op_type == "MEASURE":
            for q, c in zip(op.targets, op.classicalTargets):
                lines.append(f"qc.measure({q}, {c})")

        elif op_type == "RESET":
            for q in op.targets:
                lines.append(f"qc.reset({q})")

        elif op_type in ("BARRIER", "DIRECTIVE"):
            targets_str = ", ".join(str(t) for t in op.targets)
            lines.append(f"qc.barrier({targets_str})")

    lines.append("")
    return "\n".join(lines)


def to_cirq(circuit: CircuitIR) -> str:
    """Produces executable Python Google Cirq code."""
    lines = [
        "# Generated by Quantum Lens AI Compiler",
        "import cirq",
        "import numpy as np",
        "",
        f"qubits = cirq.LineQubit.range({circuit.qubits})",
        "circuit = cirq.Circuit()",
        "",
    ]

    cirq_gate_map = {
        "H": "cirq.H",
        "X": "cirq.X",
        "Y": "cirq.Y",
        "Z": "cirq.Z",
        "S": "cirq.S",
        "T": "cirq.T",
        "SDG": "cirq.inverse(cirq.S)",
        "TDG": "cirq.inverse(cirq.T)",
        "CX": "cirq.CNOT",
        "CZ": "cirq.CZ",
        "SWAP": "cirq.SWAP",
        "CCX": "cirq.TOFFOLI",
        "CSWAP": "cirq.CSWAP",
    }

    for op in circuit.operations:
        op_type = op.type.upper()

        if op_type == "GATE":
            gate_name = op.gate.upper() if op.gate else "UNKNOWN"
            qubit_refs = [f"qubits[{c}]" for c in op.controls] + [f"qubits[{t}]" for t in op.targets]

            if gate_name in cirq_gate_map:
                cirq_op = cirq_gate_map[gate_name]
                lines.append(f"circuit.append({cirq_op}({', '.join(qubit_refs)}))")
            elif gate_name in ("RX", "RY", "RZ"):
                theta = _format_param(op.params[0]) if op.params else "0.0"
                cirq_fn = f"cirq.{gate_name.lower()}({theta})"
                lines.append(f"circuit.append({cirq_fn}({qubit_refs[0]}))")
            elif gate_name == "P":
                lam = _format_param(op.params[0]) if op.params else "0.0"
                lines.append(f"circuit.append(cirq.ZPowGate(exponent={lam}/np.pi)({qubit_refs[0]}))")
            else:
                lines.append(f"# Gate {gate_name} mapped as custom operation")

        elif op_type == "MEASURE":
            for q, c in zip(op.targets, op.classicalTargets):
                lines.append(f"circuit.append(cirq.measure(qubits[{q}], key='c[{c}]'))")

        elif op_type == "RESET":
            for q in op.targets:
                lines.append(f"circuit.append(cirq.reset(qubits[{q}]))")

        elif op_type in ("BARRIER", "DIRECTIVE"):
            lines.append(f"# Barrier across: {op.targets}")

    lines.append("")
    return "\n".join(lines)


def to_pennylane(circuit: CircuitIR) -> str:
    """Produces executable Python Xanadu PennyLane code."""
    lines = [
        "# Generated by Quantum Lens AI Compiler",
        "import pennylane as qml",
        "import numpy as np",
        "",
        f"dev = qml.device('default.qubit', wires={circuit.qubits})",
        "",
        "@qml.qnode(dev)",
        "def circuit():",
    ]

    pennylane_map = {
        "H": "qml.Hadamard",
        "X": "qml.PauliX",
        "Y": "qml.PauliY",
        "Z": "qml.PauliZ",
        "S": "qml.S",
        "T": "qml.T",
        "SDG": "qml.adjoint(qml.S)",
        "TDG": "qml.adjoint(qml.T)",
        "CX": "qml.CNOT",
        "CZ": "qml.CZ",
        "CY": "qml.CY",
        "CH": "qml.CH",
        "SWAP": "qml.SWAP",
        "CCX": "qml.Toffoli",
        "CSWAP": "qml.CSWAP",
    }

    indent = "    "
    for op in circuit.operations:
        op_type = op.type.upper()

        if op_type == "GATE":
            gate_name = op.gate.upper() if op.gate else "UNKNOWN"
            qubits = list(op.controls) + list(op.targets)

            if gate_name in pennylane_map:
                fn = pennylane_map[gate_name]
                if len(qubits) == 1:
                    lines.append(f"{indent}{fn}(wires={qubits[0]})")
                else:
                    lines.append(f"{indent}{fn}(wires={qubits})")
            elif gate_name in ("RX", "RY", "RZ"):
                theta = _format_param(op.params[0]) if op.params else "0.0"
                lines.append(f"{indent}qml.{gate_name}({theta}, wires={qubits[0]})")
            elif gate_name == "P":
                phi = _format_param(op.params[0]) if op.params else "0.0"
                lines.append(f"{indent}qml.PhaseShift({phi}, wires={qubits[0]})")
            elif gate_name in ("CRX", "CRY", "CRZ"):
                theta = _format_param(op.params[0]) if op.params else "0.0"
                lines.append(f"{indent}qml.{gate_name}({theta}, wires={qubits})")

        elif op_type == "MEASURE":
            # PennyLane typically samples or measures at the end of the QNode
            pass

    lines.append(f"{indent}return qml.state()")
    lines.append("")
    return "\n".join(lines)


def generate_code(circuit: CircuitIR, format: ExportFormat) -> str:
    """Authoritative entry point for framework code generation."""
    fmt = format.lower()
    if fmt in ("openqasm3", "qasm", "qasm3"):
        return to_openqasm3(circuit)
    elif fmt == "qiskit":
        return to_qiskit(circuit)
    elif fmt == "cirq":
        return to_cirq(circuit)
    elif fmt == "pennylane":
        return to_pennylane(circuit)
    else:
        raise ValueError(f"Unsupported export format '{format}'. Supported: openqasm3, qiskit, cirq, pennylane")
